import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
  OrganizationSwitcher
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="flex justify-between items-center px-4 py-2 border-b">
  <SignedIn>
    <div className="flex items-center gap-4">
      <OrganizationSwitcher
  afterCreateOrganizationUrl="/org/:slug/dashboard"
  afterSelectOrganizationUrl="/org/:slug/dashboard"
  appearance={{
    elements: {
      rootBox: "w-[200px]",
    },
  }}
/>

      <UserButton />
    </div>
  </SignedIn>
  <SignedOut>
    <div className="flex gap-2">
      <SignInButton />
      <SignUpButton />
    </div>
  </SignedOut>
</header>

          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}